language : node_js
node_js :
 - stable
install :
 - npm install
script: 
 - npm test

# Send coverage data to Coveralls
after_script: "cat coverage/coverage.json | node_modules/coveralls/bin/coveralls.js"