language : node_js
node_js :
 - stable
install :
 - "npm install && npm run build"

script: 
 - npm test

before_deploy:
  - "npm run release"
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+

# Send coverage data to Coveralls
after_success:
  - "npm run coverage"